<?xml version='1.0'?>

<robot name="udacity_bot_sebastian" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Include Gazebo plugins -->
<xacro:include filename="$(find slam_project)/urdf/udacity_bot_sebastian.gazebo"/>

<!-- Wheel Parameters -->
<xacro:property name="wheel_mass" value="5.0" />
<xacro:property name="wheel_radius" value="0.075" />
<xacro:property name="wheel_thickness" value="0.05" />

<!-- Body Parameters -->
<xacro:property name="chassis_mass" value="10.0" />
<xacro:property name="lidar_mount_mass" value="5.0" />

<!-- Materials -->
<material name="black">
    <color rgba="0.2 0.2 0.2 1"/>
</material>
<material name="gray">
    <color rgba="0.6 0.6 0.6 1"/>
</material>
<material name="red">
    <color rgba="0.8 0.0 0.0 1"/>
</material>

  <!-- ROBOT FOOTPRINT -->
  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <!-- CHASSIS -->
  <link name='chassis'>
    <pose>0 0 0.1 0 0 0</pose>
    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>
    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size="0.3 0.4 0.1"/>
      </geometry>
    </collision>
    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="0.4 0.25 0.1"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <!-- CHASSIS/REAR CASTER -->
    <collision name='back_caster_collision'>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.049"/>
      </geometry>
    </collision>

    <visual name='back_caster_visual'>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>
    
    <!-- CHASSIS/FRONT CASTER -->
    <collision name='front_caster_collision'>
      <origin xyz="0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.049"/>
      </geometry>
    </collision>

    <visual name='front_caster_visual'>
      <origin xyz="0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>
    
  </link>

  <!-- LEFT FRONT WHEEL -->
  <link name='left_front_wheel'>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>
    <visual name='left_front_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision name='left_front_wheel_collision'>
      <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
      <geometry>
        <cylinder radius="${wheel_radius-0.00001}" length="${wheel_thickness-0.00001}"/>
      </geometry>
    </collision>
  </link>
  <joint type="continuous" name="left_front_wheel_joint">
    <origin xyz="0.0 0.175 -0.025" rpy="0 0 0"/>
    <child link="left_front_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- RIGHT FRONT WHEEL -->
  <link name='right_front_wheel'>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>
    <visual name='right_front_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision name='right_front_wheel_collision'>
      <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
      <geometry>
        <cylinder radius="${wheel_radius-0.00001}" length="${wheel_thickness-0.00001}"/>
      </geometry>
    </collision>
  </link>
  <joint type="continuous" name="right_front_wheel_joint">
    <origin xyz="0.0 -0.175 -0.025" rpy="0 0 0"/>
    <child link="right_front_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- CAMERA -->
  <link name='camera'>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"
      />
    </inertial>
    <visual name='camera_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>
    <collision name='camera_collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.0499 0.0499 0.0499"/>
      </geometry>
      <material name="black"/>
    </collision>
  </link>

  <joint type="fixed" name="camera_joint">
    <origin xyz="0.1 0 0.05" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="chassis"/>
  </joint> 
  
  <!-- OPTICAL FRAME: Workaround needed so depth cloud points in the right direction -->
  <joint name="camera_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera"/>
    <child link="camera_link_optical"/>
  </joint>
  <link name="camera_link_optical">
  </link>
  <!-- END OPTICAL FRAME -->

  <!-- LIDAR -->
    <link name='lidar_mount'>
    <inertial>
      <mass value="${lidar_mount_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="1e-3" ixy="0" ixz="0"
          iyy="1e-3" iyz="0"
          izz="1e-3"
      />
    </inertial>
    <visual name='lidar_mount_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.15 0.1"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link> 
  <joint type="fixed" name="lidar_mount_joint">
    <origin xyz="0.0 0 0.075" rpy="0 0 0"/>
    <child link="lidar_mount"/>
    <parent link="chassis"/>
  </joint> 
  
  <link name='hokuyo'>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"
      />
    </inertial>
    <visual name='hokuyo_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://slam_project/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
    <collision name='hokuyo_collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
  </link>
  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="0.0 0.0 0.075" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="lidar_mount"/>
  </joint> 
 
</robot>

